// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANvt61Y-QNbmQDRibXDYZtkvWEK_x4El8',
    appId: '1:235504198579:web:08944ad8c14a1eb96521c6',
    messagingSenderId: '235504198579',
    projectId: 'user-app-f8b2f',
    authDomain: 'user-app-f8b2f.firebaseapp.com',
    storageBucket: 'user-app-f8b2f.appspot.com',
    measurementId: 'G-XRTSL46H71',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkevjwQljs1fq3CYVljqXJR5Va7bulaP0',
    appId: '1:235504198579:android:3248052e7b04a7836521c6',
    messagingSenderId: '235504198579',
    projectId: 'user-app-f8b2f',
    storageBucket: 'user-app-f8b2f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGHxpGCFPq3vqtgLWW1h7bUWhjUnLWOiI',
    appId: '1:235504198579:ios:ea16884aea9c55c26521c6',
    messagingSenderId: '235504198579',
    projectId: 'user-app-f8b2f',
    storageBucket: 'user-app-f8b2f.appspot.com',
    iosBundleId: 'com.example.flutterTaskUserApp',
  );
}
